"""Scientific settings shared by the current point-model experiments.

FNO and LSTM use the same point cohorts, seven static predictors, calendar,
observation-event encoding, spatial split, and deterministic model seeds.
"""

from LSTM.settings import (
    AREAS,
    CONTEXT_END_DATE,
    CONTEXT_START_DATE,
    MODEL_HOLDOUT_START_DATE,
    MODEL_INPUT_METADATA_COLUMNS,
    MODEL_SEEDS,
    OBSERVATION_GAP_SCALE_DAYS,
    OPTUNA_SEED,
    PRODUCTS,
    PRODUCT_SETTINGS,
    SPATIAL_SPLIT_SEED,
    SPATIAL_TRAIN_FRACTION,
    STATIC_FEATURES,
    TARGET_VARIABLE,
    VALIDATION_START_DATE,
    WINDOW_SIZE,
    build_observation_sequences,
    context_period_indices,
    dates_from_variable,
    read_point_series,
    split_boundaries,
    summarize_ensemble,
    validate_product,
    validate_static_columns,
)

__all__ = [
    "AREAS",
    "CONTEXT_END_DATE",
    "CONTEXT_START_DATE",
    "MODEL_HOLDOUT_START_DATE",
    "MODEL_INPUT_METADATA_COLUMNS",
    "MODEL_SEEDS",
    "OBSERVATION_GAP_SCALE_DAYS",
    "OPTUNA_SEED",
    "PRODUCTS",
    "PRODUCT_SETTINGS",
    "SPATIAL_SPLIT_SEED",
    "SPATIAL_TRAIN_FRACTION",
    "STATIC_FEATURES",
    "TARGET_VARIABLE",
    "VALIDATION_START_DATE",
    "WINDOW_SIZE",
    "build_observation_sequences",
    "context_period_indices",
    "dates_from_variable",
    "read_point_series",
    "split_boundaries",
    "summarize_ensemble",
    "validate_product",
    "validate_static_columns",
]
